name: Bug report
description: |
  This is not a forum or a help section, this is strictly developer oriented.
  A 2nd line is present here.
body:

  - type: markdown
    id: info
    value: |
      ## Welcome!
      This is not a forum or a help section, this is strictly developer oriented.
      A 2nd line is present here.
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the actual behavior of the bug
    validations:
      required: true
