name: Bug report
description: |
 Report a bug with RetroPie-Setup scripts.
body:

  - type: markdown
    id: info
    attributes:
      value: |
        ## Reporting a bug
        **DO NOT** use this issue for general support questions or installation assistance,
        use the [RetroPie forums](https://retropie.org.uk/forum)
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the actual behavior of the bug
    validations:
      required: true
